/* Generated By:JavaCC: Do not edit this line. lexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 3;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int WORDMIN = 5;
  /** RegularExpression Id. */
  int WORDMAYUS = 6;
  /** RegularExpression Id. */
  int WORD = 7;
  /** RegularExpression Id. */
  int SPECIAL = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<SPACE>",
    "<NUMBER>",
    "<WORDMIN>",
    "<WORDMAYUS>",
    "<WORD>",
    "<SPECIAL>",
    "<IDENTIFIER>",
  };

}
